# Generated by Django 5.2.4 on 2025-09-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('upi', 'UPI'), ('paypal', 'PayPal'), ('netbanking', 'Net Banking')], max_length=50),
        ),
    ]
