# Generated by Django 5.2.4 on 2025-08-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customerprofile',
            managers=[
            ],
        ),
    ]
